name: lokapandu
description: "Lokapandu Flutter Project"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.1
  envied: ^1.2.1
  build_runner: ^2.7.1
  firebase_core: ^4.1.0
  firebase_ai: ^3.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  get_it: ^8.2.0
  flutter_svg: ^2.2.1
  lottie: ^3.3.2
  cached_network_image: ^3.4.1
  iconify_design: ^1.0.1
  intl: ^0.20.2

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^1.2.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
